name: ExampleBuildToolsManagement
options:
  xcodeVersion: "12.5.1"
  deploymentTarget:
    iOS: "13.0"
  groupSortPosition: top
packages:
  Kingfisher:
    url: https://github.com/onevcat/Kingfisher.git
    version: 6.3.1
  SVGKit:
    url: https://github.com/SVGKit/SVGKit.git
    version: 3.0.0
targets:
  ExampleBuildToolsManagement:
    type: application
    platform: iOS
    info:
      path: ExampleBuildToolsManagement/Resources/Info.plist
      properties:
        UILaunchStoryboardName: LaunchScreen
    settings:
      base:
        TARGETED_DEVICE_FAMILY: 1
        PRODUCT_BUNDLE_IDENTIFIER: io.github.hugehoge.ExampleBuildToolsManagement
    sources:
      - path: ExampleBuildToolsManagement
        excludes:
          - "**/.gitkeep"
      - path: ExampleBuildToolsManagement/Generated/IB-Scenes+Generated.swift
        group: ExampleBuildToolsManagement/Generated
        optional: true
    preBuildScripts:
      - name: SwiftGen
        script: |
          ${SRCROOT}/bin/swiftgen
        outputFiles:
          - ${SRCROOT}/ExampleBuildToolsManagement/Generated/IB-Scenes+Generated.swift
        basedOnDependencyAnalysis: no
      - name: LicensePlist
        script: |
          ${SRCROOT}/bin/license-plist \
          --suppress-opening-directory \
          --fail-if-missing-license \
          --output-path "${SRCROOT}/ExampleBuildToolsManagement/Resources/Settings.bundle"
        outputFiles:
          - ${SRCROOT}/ExampleBuildToolsManagement/Resources/Settings.bundle
      - name: Format and linting
        script: |
          ${SRCROOT}/bin/swiftformat --swiftversion 5.4 ExampleBuildToolsManagement/
          ${SRCROOT}/bin/swiftlint
          ${SRCROOT}/bin/iblinter
    dependencies:
      - package: Kingfisher
      - package: SVGKit
